<?php $currentPage = "kfuss | Clusters";include "inc/html-top-k.inc";?>

	<?php include "inc/nav-k.inc"; ?>

	<main>
		<h1>DMS Major</h1>
		<p>As I progress through this major, it's exciting to be able to move beyond the introductory courses and choose others that are unique to the topics that I am interested in. This semester I will be taking The Art of Film and Modern Architecture, both of which are subjects that are very new to me, but I am eager to learn more about. I am also continuing this CSC web development series, after taking CSC 170 last spring, and although I do not intend on pursuing computer science as a career, I think the fundamental skills learned are invaluable as the world becomes more digitized and driven by technology.</p>

	</main>
<?php include "inc/main-nav.inc"; ?>

	<?php include "inc/footer.php";?